### ISSUE TITLE
FileRequestTest tests failing on Windows

### ISSUE THREAD

**Issue by FrelliBB** [bastion-dev/Bastion#77]
```
java.nio.file.InvalidPathException: Illegal char <:> at index 9: classpath:/json/create_sushi_request.json
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at rocks.bastion.core.FileRequest.guessResourceMimeType(FileRequest.java:274)
```

All tests in `FileRequestTest` are failing due to this exception.

**Comment by KPull** [comment]
Same problem as #63.

**Comment by FrelliBB** [comment]
It's a different problem. It is failing here cause of the "classpath:" in the path. I did a quick check and without the "classpath:", the test passes successfully.

**Comment by KPull** [comment]
Ah, I understand. Can you please post the exception you're getting?

**Comment by FrelliBB** [comment]
I posted the exception on the first comment of the issue.

**Comment by FrelliBB** [comment]
Resolved with https://github.com/bastion-dev/Bastion/issues/89
